var imageSrc = {
	map:"map.png",
	pacman: 'pacman.png',
	blinky: 'blinky.png',
	pinky: 'pinky.png',
	bob: 'bob.png',
	paul: 'paul.png',
	fear: 'fear.png',
	blinkyFear: 'blinkyFear.png',
	pinkyFear: 'pinkyFear.png',
	bobFear: 'bobFear.png',
	paulFear: 'paulFear.png',
	fearPreTimeout: 'fearPreTimeout.png',
	dead: 'dead.png',
	cord: 'cord.png',
	tosty: 'tosty.png',
	eyes: 'eyes.png',
	brick: 'brick.png',
	shock: 'shock.png',
	gainX2: 'gainX2.png',
	gainX3: 'gainX3.png',
	elt: 'elt.png',
	fireOfShot: 'fireOfShot.png',
	blood: "blood.png",
	bloodLine: 'bloodLine.png',
	shockParticle: 'shockParticle.png',
	cursorParticle: 'cursorParticle.png',
	shocked: 'shocked.png',
	bomb: "bomb.png",
	cursor: 'cursor.png',
	bombParticle: 'bombParticle.png',
	smokeParticle: 'smokeParticle.png',
	star: "star.png",
	quadshot: "quadshot.png",
	gray: "gray.png",
	finishHim: "finishHim.png",
	boomblood: 'boomblood.png',
	fatality: 'fatality.png',
	ball: "ball.png",
	fhcursor: 'fhcursor.png'
}

var imageIconsSrc = {
	cord: 'cordIcon.png',
	bomb: 'bombIcon.png',
	shot: 'shotIcon.png',
	shock: 'shockIcon.png',
	fatality: 'fatalityIcon.png'
}

var audioSrc = {
	bitch: 'bitch.mp3',
	getOverHere: 'goh.mp3',
	bones: 'bones.mp3',
	tosty: 'tosty.mp3',
	dead: 'dead.mp3',
	begin: 'begin.mp3',
	step: 'step.mp3',
	eatghost: 'eatghost.mp3',
	signal: 'signal.mp3',
	fear: 'fear.mp3',
	scream: 'scream.mp3',
	shot: 'shot.mp3',
	shop: 'shop.mp3',
	quadshot: "quadshot.mp3",
	carmaggedon: 'carmaggedon.mp3',
	carmaggedon2: 'carmaggedon2.mp3',
	dominion: 'dominion.mp3',
	fon: 'fon.mp3',
	quaddamage: "quaddamage.mp3",
	finishHimFx: 'finishHimFx.mp3',
	finishHimFx2: 'finishHimFx2.mp3',
	finishHimFon: 'finishHimFon.mp3',
	boomdeath: 'boomdeath.mp3',
	fatality: 'fatality.mp3',
	haha: 'haha.mp3'
}

var audioMessSrc = {
	firstblood: 'firstblood.mp3',
	doublekill: 'doublekill.mp3',
	multikill: 'multikill.mp3',
	megakill: 'megakill.mp3',
	rampage: 'rampage.mp3',
	unstoppable: 'unstoppable.mp3',
	dominating: 'dominating.mp3',
	headshot: 'headshot.mp3',
	killingspree: 'killingspree.mp3',
	godlike: 'godlike.mp3',
	headHunter: 'headHunter.mp3',
	finishHim: 'finishHim.mp3'
}